### ISSUE TITLE
NQ() metrics concern

### ISSUE THREAD

**Issue by derekpowell** [aryopg/decore#7]
First off, thanks for this great work putting together this excellent testing harness. I am planning/hoping to leverage and cite this for a paper I'm working on. To that end, I did want to ask a question/raise concern about the the metrics for NQ and NQ-swap. 

In `from src.metrics.nq` in `NQ()` there's this line:

```python
# Only consider until \n, ., or ,
prediction = re.split("\n|\.|\,", sample["predicted_answer"])[0] 
```

My concern is that splitting on commas and periods in particular could cause problems for certain valid answers, such as dates (e.g. "September 5, 1985" or "c. 200 BCE") or abbreviations. What do you think? Is this just for efficiency or is there some other reason to clip the responses before computing the metrics? Thanks!

**Comment by aryopg** [comment]
Hi @derekpowell , massive thanks for the kind words and more importantly for spotting this! It was indeed written for efficiency, but as you mentioned it may cause discrepancies in the evaluation results (i.e., over-penalising the predictions). I'll re-run the evaluation (at least on NQ-Open first), and report back to you here!

**Comment by aryopg** [comment]
Hey @derekpowell , i'm back with new results on the Oracle setup of NQ-Open!

```
| Model              | Old   | New   |
| ------------------ | ----- | ----- |
| Llama3-8b-Instruct | 69.68 | 77.59 |
| + ITI              | 56.16 | 62.34 |
| + CAD              | 69.83 | 77.29 |
| + DoLA (low)       | 69.68 | 77.55 |
| + DoLA (high)      | 69.49 | 77.40 |
| + AD               | 68.93 | 76.69 |
| + DeCoRe-Static    | 70.62 | 78.64 |
| + DeCoRe-Entropy   | 70.66 | 78.68 |
```

The trend remains the same (DeCoRe yields the most accurate results), but indeed we have over-penalised the predictions in the current implementation. We will investigate the other experiment results that are affected by this too. Thanks again! Let me know if you have any follow-up questions/comments!

**Comment by derekpowell** [comment]
Glad I could help! Thanks so much for your fast reply and fix. I assume you just replaced that line with:

```python
prediction = sample['predicted_answer']
```

That look right?

**Comment by aryopg** [comment]
I still keep it like this for efficiency:
```
prediction = re.split("\n", sample["predicted_answer"])[0]
```

But do adjust it to your use cases. The one you presented works nicely if `\n` will likely be in your model's answer!

Massive thanks again @derekpowell , don't hesitate to reach out if you find something else!

**Comment by derekpowell** [comment]
Makes sense, I'll close this now, thanks!
